releases/20180120164205/config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :firmware_images
  resources :wines
  resources :grapes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'sessions/new'

  get 'users/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'index#home'
  get '/about', to: 'index#about', as: 'about'
  get '/grow', to: 'index#grow', as: 'grow'
  get '/contact', to: 'index#contact', as: 'contact'
  get '/top-:category/:company', to: 'index#place', as: 'place'
  get '/top-:category', to: 'index#ranking', as: 'ranking'
  get '/search', to: 'index#search', as: 'search'
  get '/shareup/:id', to: 'index#share_up', as: 'shareup'
  get '/likeup/:id', to: 'index#like_up', as: 'likeup'
  get '/wines', to: 'wines#index'
  get '/wine_week', to: 'wines#week'
  get '/grape_week', to: 'grapes#week'
  get '/groups', to: 'groups#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
   resources :users
  
  scope 'admin' do
    resources :companies
  end

  root 'index#home'

end

releases/20180120164205/app/models/wine.rb
class Wine < ApplicationRecord
end

releases/20180120164205/app/controllers/wines_controller.rb
class WinesController < InheritedResources::Base

	def index

		@wines = Wine.where(publish: '1')
		
	end

	def week

		@wines = Wine.where(publish: '1',week_pub: '1')

	end

end

releases/20180120164205/app/helpers/wines_helper.rb
module WinesHelper
end

releases/20180120164205/app/views/wines/_form.html.erb
<%= form_for(wine) do |f| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :short_des %>
    <%= f.text_field :short_des %>
  </div>

  <div class="field">
    <%= f.label :long_des %>
    <%= f.text_area :long_des %>
  </div>

  <div class="field">
    <%= f.label :pic %>
    <%= f.text_field :pic %>
  </div>

  <div class="field">
    <%= f.label :regions %>
    <%= f.text_field :regions %>
  </div>

  <div class="field">
    <%= f.label :wine %>
    <%= f.text_field :wine %>
  </div>

  <div class="field">
    <%= f.label :publish %>
    <%= f.check_box :publish %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

releases/20180120164205/app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

releases/20180120164205/app/views/wines/index.html.erb
<% provide(:body_class, "ranking-page") %>
<!--Start of Banner section-->
<section class="main-banner-section">
    <div class="container-fluid no-padding">
        <div class="banner-container banner-container-wine">
            <div class="container">
                <div class="row">
                    <div class="category-title col-xs-12 col-sm-12 col-lg-12">
                        <span class="separator">Top Wine|</span>
                        <span class="date-container "> <%= DateTime.now.strftime "%B %Y" %></span>
                    </div>
                    <h1 class="places-container col-xs-12 col-sm-12 col-lg-12">Wine</h1>
                </div>
            </div>
        </div>
    </div>
</section>
<!--End of Banner section-->

<!--Start of places list section-->
<section class="places-list-section">
    <% @wines.each_with_index do |wine, index| %>
    <div class="social-modal">
        <div class="container">
          <h1>Share</h1>
          <%= social_share_button_tag(wine.name, :image => asset_path("images-places-#{index+1}.png")) %>
          <span class="glyphicon glyphicon-remove-circle"></span>
      </div>                          
  </div>
  <!--Start of place cont-->
  <div class="container-fluid no-padding">
    <div class="place-container container">
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-4 image-container no-padding hidden-sm hidden-xs">
                  <a href="<%= wines_path%>">
                      <img src="uploads/<%= wine.pic%>" class="img-responsive">
                  </a>
              </div>
              <div class="col-md-8 col-sm-12 col-xs-12 info-container">
                <div class="header-section">
                    <div class="number-container"><%= index+1 %></div>
                    <div class="separator"></div>
                    <div class="name-container">
                        <div class="title-container"><%= set_title wine.name %></div>
                    </div>
                </div>
                <div class="image-for-mobile hidden-lg hidden-md">
                    <%= image_tag "images-places-#{index+1}.png", class: 'img-responsive' %>
                </div>
                <div class="main-text-container">
                    <p>
                      <%= wine.short_des %>
                  </p>
              </div>
              <div class="wine-long_description">
                <span>
                    <%= wine.long_des %>
                </span>
            </div>
            <div class="wine-region">
               <strong class="text-info" >Regions:</strong><span style="margin-left: 14px">
                <% unless wine.regions == nil %>
                <% wine.regions.split(',').each do |element| %>
                <a href="#">
                  <span class="regions-element"><%=  element %></span>
                  <% end %>
              </span>
                </a>
            <% end %>
            </div>
              <div class="wine-supplyer">
                 <strong class="text-info">Supplyer:</strong>
                 <span style="margin-left: 14px">
                    <% unless wine.supply == nil %>
                    <% wine.supply.split(',').each_with_index do |element,index| %>
                    <a href="<%= wine.supply_url.split(',').fetch(index) %>">
                      <span class="regions-element"><%=  element %></span>
                      <% end %>
                    </span>
                    </a>
                    <% end %>
                </span>
            </div>

</div>
</div>
</div>
</div>
</div>
<!--end of place container-->                          
<% end %>    
</section>
<section class="place-slider-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12 b_slider_wrapper">
        <h1>Related wines</h1>
        <div class="b_slider">
          <%= image_tag 'Aglianico_del_Vulture_new.jpg', class: 'b_slider__slide img-responsive' %>
          <%= image_tag 'Albarola_new.jpg', class: 'b_slider__slide img-responsive' %>
          <%= image_tag 'Avana_new.jpg', class: 'b_slider__slide img-responsive' %>
          <%= image_tag 'Avana_new.jpg', class: 'b_slider__slide img-responsive' %>
          <%= image_tag 'Avana_new.jpg', class: 'b_slider__slide img-responsive' %>
          <%= image_tag 'Avana_new.jpg', class: 'b_slider__slide img-responsive' %>
          <%= image_tag 'Avana_new.jpg', class: 'b_slider__slide img-responsive' %>
        </div>
      </div>
    </div>
  </div>
</section>

releases/20180120164205/app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

releases/20180120164205/app/views/wines/show.html.erb
<% provide(:body_class, "place-page") %>
<!--Start of banner section-->
<section class="main-banner-section">
  <div class="container-fluid no-padding">
    <div class="banner-container">
      <div class="container">
        <div class="row">
          <div class="text-container">
            <h1>
              <div class="category-title col-xs-12 col-sm-12 col-lg-12">
                <span class="number"><%= @no %> <span class="separator"></span></span>
                <span class="category-name"><%= @wine.name %></span>
              </div>
              <div class="location-wrapper col-xs-12 col-sm-12 col-lg-12">
                <div class="share-container col-md-2 hidden-md hidden-lg  no-padding">
                </div>
              </div>
            </h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!--end of banner section-->
<div class="social-modal">
  <div class="container">
    <h1>Share</h1>
    <span class="glyphicon glyphicon-remove-circle"></span>
  </div>
</div> 

<!--Start of main info container-->
<section class="main-info-container">
  <div class="container">
    <div class="row">
      <div class="col-md-4 map-container">
        <span>
          <%= link_to image_tag( "/uploads/" + @wine.pic, class: 'img-responsive' )%>
        </span>
      </div>
      <div class="col-md-8 text-container">
        <div class="wine-title">
          <h1 class="text-left"><%= @wine.name %></h1>
        </div>
        <div class="wine-short_description">
          <span class="">
           <%= @wine.short_des %>
         </span>
       </div>
       <div class="wine-long_description">
        <span>
         <%= @wine.long_des %>
       </span>
     </div>
     <div class="wine-region">
       <strong class="text-info" >Regions:</strong><span style="margin-left: 14px">
        <% unless @wine.regions == nil %>
        <% @wine.regions.split(',').each do |element| %>
        <a href="#">
          <span class="regions-element "><%=  element %></span>
          <% end %>
        </span>
      </a>
      <% end %>
    </div>
    <div class="wine-supplyer">
     <strong class="text-info">Supplyer:</strong>
      <span style="margin-left: 14px">
        <% unless @wine.supply == nil %>
        <% @wine.supply.split(',').each_with_index do |element,index| %>
        <a href="<%= @wine.supply_url.split(',').fetch(index) %>">
          <span class="regions-element "><%=  element %></span>
          <% end %>
        </span>
        </a>
        <% end %>
      </span>
  </div>
</div>
</div>
</div>
</section>
<!--end of main info container -->
<section class="place-slider-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12 b_slider_wrapper">
        <h1>Related wines</h1>
        <div class="b_slider">
          <%= image_tag 'Aglianico_del_Vulture_new.jpg', class: 'b_slider__slide img-responsive' %>
          <%= image_tag 'Albarola_new.jpg', class: 'b_slider__slide img-responsive' %>
          <%= image_tag 'Avana_new.jpg', class: 'b_slider__slide img-responsive' %>
          <%= image_tag 'Avana_new.jpg', class: 'b_slider__slide img-responsive' %>
          <%= image_tag 'Avana_new.jpg', class: 'b_slider__slide img-responsive' %>
          <%= image_tag 'Avana_new.jpg', class: 'b_slider__slide img-responsive' %>
          <%= image_tag 'Avana_new.jpg', class: 'b_slider__slide img-responsive' %>
        </div>
      </div>
    </div>
  </div>
</section>

releases/20180120164205/app/views/wines/week.html.erb
<% provide(:body_class, "ranking-page") %>
<!--Start of Banner section-->
<section class="main-banner-section">
    <div class="container-fluid no-padding">
        <div class="banner-container banner-container-wine-week">
            <div class="container">
                <div class="row">
                    <div class="category-title col-xs-12 col-sm-12 col-lg-12">
                        <span class="separator">Wine of the week |</span>
                        <span class="date-container "> <%= DateTime.now.strftime "%B %Y" %></span>
                    </div>
                    <h1 class="places-container col-xs-12 col-sm-12 col-lg-12">Wine</h1>
                </div>
            </div>
        </div>
    </div>
</section>
<!--End of Banner section-->

<!--Start of places list section-->
<section class="places-list-section">
<% @wines.each_with_index do |wine, index| %>
  <div class="social-modal">
    <div class="container">
      <h1>Share</h1>
      <%= social_share_button_tag(wine.name, :image => asset_path("images-places-#{index+1}.png")) %>
      <span class="glyphicon glyphicon-remove-circle"></span>
    </div>                          
  </div>
    <!--Start of place cont-->
    <div class="container-fluid no-padding">
        <div class="place-container container">
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-4 image-container no-padding hidden-sm hidden-xs">
                      <a href="<%= wines_path%>">
                      <img src="uploads/<%= wine.pic%>" class="img-responsive">
                      </a>
                    </div>
                    <div class="col-md-8 col-sm-12 col-xs-12 info-container">
                        <div class="header-section">
                            <div class="number-container"><%= index+1 %></div>
                            <div class="separator"></div>
                            <div class="name-container">
                                <div class="title-container"><%= set_title wine.name %></div>
                            </div>
                        </div>
                        <div class="image-for-mobile hidden-lg hidden-md">
                            <%= image_tag "images-places-#{index+1}.png", class: 'img-responsive' %>
                        </div>
                        <div class="main-text-container">
                            <p>
                              <%= wine.long_des %>
                            </p>
                        </div>
                        <div class="social-container">
                                <div class="share-container">
                                    <div class="share-button">
                                        <%= link_to shareup_path( wine.id ), remote: true do %>
                                            <span class="text hidden-xs hidden-sm">Share</span>
                                            <span class="share-icon"></span>
                                            <span class="separator "></span>
                                            <div class="share-count " id = "share-text-<%= wine.id %>"><%= wine.share %></div>
                                        <% end %>
                                    </div>

                                </div>
                                <div class="like-container">
                                    <div class="like-button">
                                        <%= link_to likeup_path( wine.id ), remote: true do %>
                                            <span class="text hidden-xs hidden-sm">Like</span>
                                            <span class="like-icon"></span>
                                            <span class="separator "></span>
                                            <div class="like-count " id = "like-text-<%= wine.id %>"><%= wine.like %></div>
                                        <% end %>
                                    </div>
                                </div>
                          </div>
                        <div class="buttons-container">
                            <div class="learn-more-button"><%= link_to "READ MORE", wine %></div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--end of place container-->                          
<% end %>    
</section>