releases/20180120164205/config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :firmware_images
  resources :wines
  resources :grapes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'sessions/new'

  get 'users/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'index#home'
  get '/about', to: 'index#about', as: 'about'
  get '/grow', to: 'index#grow', as: 'grow'
  get '/contact', to: 'index#contact', as: 'contact'
  get '/top-:category/:company', to: 'index#place', as: 'place'
  get '/top-:category', to: 'index#ranking', as: 'ranking'
  get '/search', to: 'index#search', as: 'search'
  get '/shareup/:id', to: 'index#share_up', as: 'shareup'
  get '/likeup/:id', to: 'index#like_up', as: 'likeup'
  get '/wines', to: 'wines#index'
  get '/wine_week', to: 'wines#week'
  get '/grape_week', to: 'grapes#week'
  get '/groups', to: 'groups#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
   resources :users
  
  scope 'admin' do
    resources :companies
  end

  root 'index#home'

end

releases/20180120164205/app/views/index/contact.js.erb
$('#email-alert').html("<strong><%= @result %>!</strong><%= @result %> to send email...").fadeIn(1000).fadeOut(1000);

releases/20180120164205/app/views/index/home.html.erb
<% provide(:title, "Grapedia") %>
<% provide(:body_class, " ") %>
 <!--Start Search Section-->
  <section class="search-section">
    <div class="container-fluid background-image san-franc">
      <div class="container">
        <div class="row">
          <div class="col-centered quoute-container col-md-12 col-sm-12 col-xs-12 col-lg-12">
            <h1>Grapedia</h1>
          </div>
        </div>
        <div class="row">
          <div class="heading-container col-centered col-md-12 col-sm-12 col-xs-12 col-lg-12">
            <span class="wow pulse" style="visibility: visible; animation-iteration-count: 3; animation-name: pulse;" data-wow-duration="0.15">Search our grape and wine list</span>
          </div>
        </div>
        <div class="row">
          <div class="search-field-container col-md-12 col-sm-12 col-xs-12 col-lg-12">
          <%= form_for(:search_form, url:search_path, :method => 'get') do |f| %>
            <div class="search-wrapper">
              <span class="search_icon"></span>
              <%= text_field_tag :search, '', placeholder: "Search by name", class:"search_field_input" %>
              <select name="search_select" id="search_select">
                <option>Wine</option>
                <option>Grape</option>
              </select>
              <%= f.submit 'Search', class: "search_button sf" %>
            </div>
          <% end %>
          </div>
        </div>
      </div>
    </div>
    <!-- <div class="container-fluid city-explore-container">
      <div class="container">
        <div class="row">
          <div class="ready-to-explore-container">
            <div class="text-container col-centered col-md-8 col-xs-12 col-lg-8 col-sm-12">
              <div class="question-container">Ready to Explore the Grape?</div>
              <div class="guide-container">Download Our Best of Wind Guide</div>
              <div class="link-container"><a class="sf" href="#"></a></div>
            </div>
          </div>
        </div>
      </div> -->

    </div>
  </section> 
    
  <!--Places Section-->
  <section class="places-section">
    <div class="container">
      <div class="row">
        <!--Large Place Container-->
        <div class="main-place-container col-md-6 col-lg-6 col-sm-12 col-xs-12 wow bounceInLeft" style="visibility: visible; animation-name: bounceInLeft;animation-delay: 0.5s;">
          <div class="place-content-container">
            <%= link_to '', grape_week_path, class: 'place-link' %>
            <%= image_tag 'original_grow-your-own-grape-vine.jpg', class: 'img-responsive', alt: 'brunch places in San Francisco' %>
            <div class="info-container">
              <div class="category-container">Grapes</div>
              <div class="title-container"><strong>Grape of the week</strong></div>
            </div>
          </div>
        </div>
        <!--End Large Place Container-->

        <!--Small places container-->
        <div class="small-places-container col-md-6 col-lg-6 col-sm-12 col-xs-12" >
          <div class="row">
            <div class="col-md-6 col-lg-6 col-xs-12 col-sm-6 place-item wow flipInX center" style="visibility: visible; animation-name: flipInX; animation-delay: 0.9s;">
              <div class="place-content-container">
                <%= link_to '', grow_path, class: 'place-link' %>
                <%= image_tag 'Albarola_new.jpg', class: 'img-responsive', alt: 'brunch places in San Francisco' %>
                <div class="info-container">
                  <div class="title-container"><strong>Help us growing</strong></div>
                  <div class="social-container">
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-lg-6 col-xs-12 col-sm-6 place-item wow bounceInRight" style="visibility: visible; animation-name: bounceInRight; animation-delay: 1.3s;">
              <div class="place-content-container">
                <%= link_to '', wine_week_path, class: 'place-link' %>
                <%= image_tag 'image-places-parks.jpg', class: 'img-responsive', alt: 'brunch places in San Francisco' %>
                <div class="info-container">
                  <div class="title-container"><strong>Wine of the week</strong> </div>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-lg-6 col-xs-12 col-sm-6 place-item wow bounceInUp center" style="visibility: visible; animation-delay: 1.7s; animation-name: bounceInUp; ">
              <div class="place-content-container">
                <%= link_to '', about_path, class: 'place-link' %>
                <%= image_tag 'image-places-travel.jpg', class: 'img-responsive', alt: 'brunch places in San Francisco' %>
                <div class="info-container">
                  <div class="title-container"><strong>About Us</strong> </div>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-lg-6 col-xs-12 col-sm-6 place-item wow bounceInUp center" style="visibility: visible; animation-delay: 2.1s; animation-name: bounceInUp; ">
              <div class="place-content-container">
                <%= link_to '', blogs_path, class: 'place-link' %>
                <%= image_tag 'image-places-brewery.jpg', class: 'img-responsive', alt: 'brunch places in San Francisco' %>
                <div class="info-container">
                  <div class="title-container"><strong>Blogs</strong></div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
</section>
  <!--We make easy section-->
<section class="we-make-easy-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12 title-container">Introduction to our </div>
      <div class="col-md-12 title-city-container">Grape Guide</div>
      <div class="separator-сontainer col-md-12">
        <div class="separator sf col-centered"></div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 wow bounceInLeft" style="visibility: visible; animation-name: bounceInLeft; animation-delay: 0.6s;" data-wow-duration="0.45">
        <div class="text-info-container">
          We have started filling our grape guide with Italian grapes, our friends at Italyabroad.com are helping us. Only Italy grows more than 1000 grapes and I will take us some time before we can list all of them and then move to the next country, so please be patient
For each grape you will find information on where the grape is grown, its history and characteristics and pairing suggestions and for each grape you will also find wines from different suppliers made with the grape. At the bottom of the page you will also see a comment form and please feel free to get in touch if you think we have forgotten something.

        </div>
      </div>
      <div class="col-md-6 wow bounceInRight" style="visibility: visible; animation-name: bounceInRight; animation-delay: 0.9s;" data-wow-duration="1.15">
        <div class="advantages-container">
          <ul class="advantages-list sf">
            <li class="advantages-item">
                <span class="text-container">
                  <div class="icon-database"></div> <div>We started as a grape guide but then, thanks to your comments and feedbacks, we decided to add a wine library</div> </span>
            </li>
            <li class="advantages-item">
                <span class="text-container">
                  <div class="icon-certificate"></div> <div>With regard to Italian wines, the first thing to say is the wine classifications </div> </span>
            </li>
            <li class="advantages-item">
                <span class="text-container">
                  <div class="icon-map"></div> <div>Wine are classified into DOCG, DOC, IGT and table wine. DOCG ......, DOC....., IGT....... and table wine........ </div> </span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>
  <!--End we make it easy section-->

  <!--Feature Section-->
<section class="feature-section">
  <div class="container-fluid img-wrapper">
    <div class="image-container">
      <div class="info-container">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="category-container">Grapedia</div>
            </div>
            <div class="col-md-12">
              <div class="title-container">Best Grape& Wines</div>
            </div>
            <div class="col-md-7 wow pulse" data-wow-duration="0.25s" style="visibility: visible; animation-duration: 0.25s; animation-iteration-count: 5; animation-name: pulse;">
              <div class="text-container">Ever wonder how wine is made? Or why some bottles of wine are more expensive than others? Here's some information for you to better understand wine and what makes its cost
              </div>
            </div>
            <div class="col-md-7">
              <div class="button-container">
                <div class="read-more-container">
                  <a href="#">READ MORE</a>
                </div>
                <div class="social-container">
                  <ul class="social-list">
                    <li class="share-button"><a href="#"></a></li>
                    <li class="like-button"><a href="#"></a></li>
                    <li class="chat-container"><a href="#"></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</section>
<!--End of Feature Section-->

<!--Learn More Section  -->
<section class="learn-more-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="title-container">
          Cheap vs. Expensive
        </div>
      </div>
      <div class="col-md-12">
        <div class="quote-container">
          Grape and wine
        </div>
      </div>
      <div class="separator-сontainer col-md-12">
        <div class="separator sf col-centered"></div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-5">
        <div class="text-container wow pulse" data-wow-duration="0.25s" data-wow-iteration="5" style="visibility: visible; animation-duration: 0.25s; animation-iteration-count: 5; animation-name: pulse;">
          <strong>So</strong> why are some wines cheap, and others are more expensive? Cheap wines are stock-picked from the vineyards and processed by machinery. The grapes are often damaged or require large amounts of pesticides to help keep rot and decay at bay. Many preservatives are added, lowering sanitation standards and decreasing production costs. When you purchase a cheap bottle of wine, you are paying for pesticides, preservatives, and low quality grapes. 
        </div>
      </div>
      <div class="col-md-7">
        <div class="progress-container">
          <ul class="progress-list">
            <li class="progress-item wow lightSpeedIn" style="visibility: visible; animation-delay: 0.5s; animation-name: lightSpeedIn;">
              <div class="icon-expert sf"></div>
              <div class="progress-name-container">EXPERT OPINIONS</div>
              <div class="progress-bar-wrapper">
                <div class="progress-bar sf" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width:45%">
                  30%
                </div>
              </div>
            </li>
            <li class="progress-item wow lightSpeedIn" style="visibility: visible; animation-delay: 0.8s; animation-name: lightSpeedIn;">
              <div class="icon-awards sf"></div>
              <div class="progress-name-container">PREVIOUS ACCOLADES</div>
              <div class="progress-bar-wrapper">
                <div class="progress-bar sf" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width:30%">
                  20%
                </div>
              </div>
            </li>
            <li class="progress-item wow lightSpeedIn" style="visibility: visible; animation-delay: 1.1s; animation-name: lightSpeedIn;">
              <div class="icon-phone sf"></div>
              <div class="progress-name-container">OTHER DATA & STATS</div>
              <div class="progress-bar-wrapper">
                <div class="progress-bar sf" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width:65%">
                  50%
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>
<!--End Learn More Section-->
  <!--Media section-->
<!--End of Media section-->
<!--City Guide Section-->

  <!--End of city guide -->

releases/20180120164205/app/views/index/like_up.js.erb
$('#like-text-<%= @company.id %>').text("<%= @like %>");

releases/20180120164205/app/views/index/place.html.erb
<% provide(:title, "#{@company.name} | Top #{Category.find(@company.category).name} in SF") %>
<% provide(:body_class, "place-page") %>
<!--Start of banner section-->
<section class="main-banner-section">
    <div class="container-fluid no-padding">
        <div class="banner-container">
            <div class="container">
                <div class="row">
                    <div class="text-container">
                        <h1>
                            <div class="category-title col-xs-12 col-sm-12 col-lg-12">
                                <span class="number"><%= @no %> <span class="separator">of <a href="/top-<%= url_code( Category.find(@company.category).name ) %>/" title="Top Brunch in SF" style="color:#787878; text-decoration: underline;">Best <%= Category.find(@company.category).name %> in SF</a></span></span>
                                <span class="category-name"><%= @company.name %></span>
                            </div>
                            <div class="location-wrapper col-xs-12 col-sm-12 col-lg-12">
                                <span class="location-container"><span class="location-icon"></span> <%= @position['address'] %></span>
                                <div class="share-container col-md-2 hidden-md hidden-lg  no-padding">
                                    <a href="#"><span class="text">Share</span><span class="icon-share"></span> <%= @company.share %> </a>
                                </div>
                            </div>
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--end of banner section-->
<div class="social-modal">
    <div class="container">
      <h1>Share</h1>
      <%= social_share_button_tag(@company.name, :image => asset_path(@position['img'])) %>
      <span class="glyphicon glyphicon-remove-circle"></span>
    </div>
</div> 
<!--Start of buttons section-->
<section class="places-buttons-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-xs-12 col-sm-12 buttons-wrapper">
                <div class="directions-container col-md-2 col-xs-3 no-padding">
                    <a href="#">Directions</a>
                </div>
                <div class="contact-container col-md-2 col-xs-3 no-padding">
                    <a href="#">Contact</a>
                </div>
                <div class="website-container col-md-2 col-xs-3 no-padding">
                    <a href="#">Website</a>
                </div>
                <div class="view-menu-container col-md-2 col-xs-3 no-padding">
                    <a href="#">View menu</a>
                </div>
                <div class="share-container col-md-2 hidden-xs hidden-sm  no-padding">
                    <%= link_to shareup_path( @company.id ), remote: true do %>
                        <span class="text">Share</span><span class="icon-share"></span> <span class="separator"></span>
                        <span id ="share-text-<%= @company.id %>"><%= @company.share %></span> 
                    <% end %>
                </div>
                <div class="like-container col-md-2 hidden-xs hidden-sm no-padding">
                    <%= link_to likeup_path( @company.id ), remote: true do %>
                        <span class="text">Like</span><span class="icon-like"></span> <span class="separator"></span>
                        <span id ="like-text-<%= @company.id %>"><%= @company.like %></span> 
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</section>
<!--end of buttons section-->

<!--Start of main info container-->
<section class="main-info-container">
    <div class="container">
        <div class="row">
            <div class="col-md-6 text-container">
                <span>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                    labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
                    nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit
                    esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt
                    in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus
                    error sit voluptatem accusantium.
                </span>
                <span>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
                    dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
                    deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem
                    accusantium.
                </span>
            </div>
            <div class="col-md-6 map-container">
                <div class="image-container" 
                style="background: url('<%= asset_path(@position['img']) %>') no-repeat center center; background-size: 100% ; height: 156px;">
                    <!-- <%= image_tag 'place-image.png', class: 'img-responsive' %> -->
                </div>
                <div class="google-map-container">
                    <div id="map"></div>
                </div>
                <script type="text/javascript">
                  function initialize() {
                        var mapCanvas = document.getElementById('map');
                        var mapOptions = {
                            center: new google.maps.LatLng(<%= @position['lat'] %>, <%= @position['lng'] %>),
                            zoom: 14
                        };
                        var map = new google.maps.Map(mapCanvas, mapOptions);
                        var icon = "<%= asset_path('icon-google-map.png') %>";
                        var pointMarker = new google.maps.Marker({
                            position: new google.maps.LatLng(<%= @position['lat'] %>, <%= @position['lng'] %>),
                            map: map,
                            icon: icon
                        });
                    }
                    // google.maps.event.addDomListener(window, 'load', initialize);
                </script>
                <script async defer src="<%= Rails.application.secrets[:google_map_url] %>key=<%= Rails.application.secrets[:google_map_key] %>&callback=initialize" type="text/javascript"></script>
                <!-- <script type="text/javascript" src="https://cdn.rawgit.com/googlemaps/v3-utility-library/master/infobox/src/infobox.js"></script>  -->
            </div>
        </div>
    </div>
</section>
<!--end of main info container -->
<section class="place-slider-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12 b_slider_wrapper">
                <div class="b_slider">
                    <%= image_tag 'place-slide-1.jpg', class: 'b_slider__slide img-responsive' %>
                    <%= image_tag 'place-slide-2.jpg', class: 'b_slider__slide img-responsive' %>
                    <%= image_tag 'place-slide-3.jpg', class: 'b_slider__slide img-responsive' %>
                    <%= image_tag 'place-slide-4.jpg', class: 'b_slider__slide img-responsive' %>
                    <%= image_tag 'place-slide-1.jpg', class: 'b_slider__slide img-responsive' %>
                    <%= image_tag 'place-slide-2.jpg', class: 'b_slider__slide img-responsive' %>
                    <%= image_tag 'place-slide-3.jpg', class: 'b_slider__slide img-responsive' %>
                    <%= image_tag 'place-slide-4.jpg', class: 'b_slider__slide img-responsive' %>
                </div>
            </div>
        </div>
    </div>
</section>

<!--end of main info container-->

releases/20180120164205/app/views/index/ranking.html.erb
<% provide(:title, "Top #{@category.name} in SF") %>
<% provide(:body_class, "ranking-page") %>
<!--Start of Banner section-->
<section class="main-banner-section">
    <div class="container-fluid no-padding">
        <div class="banner-container">
            <div class="container">
                <div class="row">
                    <div class="category-title col-xs-12 col-sm-12 col-lg-12">
                        <span class="category-name "><%= @category.name %></span>
                        <!-- Food & Drink -->
                        <span class="separator">|</span>
                        <span class="date-container "> <%= DateTime.now.strftime "%B %Y" %></span>
                    </div>
                    <h1 class="places-container col-xs-12 col-sm-12 col-lg-12">10 Best <%= @category.name %> in SF</h1>
                </div>
            </div>
        </div>
    </div>
</section>
<!--End of Banner section-->

<!--Start of places list section-->
<section class="places-list-section">
<% @companies.each_with_index do |company, index| %>
  <div class="social-modal">
    <div class="container">
      <h1>Share</h1>
      <%= social_share_button_tag(company.name, :image => asset_path("images-places-#{index+1}.png")) %>
      <span class="glyphicon glyphicon-remove-circle"></span>
    </div>                          
  </div>
    <!--Start of place cont-->
    <div class="container-fluid no-padding">
        <div class="place-container container">
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-4 image-container no-padding hidden-sm hidden-xs">
                        <%= link_to image_tag( "images-places-#{index+1}.png", class: 'img-responsive' ), place_path( url_code(Category.find(company.category).name), url_code( company.name ) ) %>                        
                    </div>
                    <div class="col-md-8 col-sm-12 col-xs-12 info-container">
                        <div class="header-section">
                            <div class="number-container"><%= index+1 %></div>
                            <div class="separator"></div>
                            <div class="name-container">
                                <div class="title-container"><%= set_title company.name %></div>
                                <div class="city-container"><span class="location-icon"></span><%= company.city %></div>
                            </div>
                            <div class="social-container">
                                <div class="share-container">
                                    <div class="share-button">
                                        <%= link_to shareup_path( company.id ), remote: true do %>
                                            <span class="text hidden-xs hidden-sm">Share</span>
                                            <span class="share-icon"></span>
                                            <span class="separator "></span>
                                            <div class="share-count " id = "share-text-<%= company.id %>"><%= company.share %></div>
                                        <% end %>
                                    </div>

                                </div>
                                <div class="like-container">
                                    <div class="like-button">
                                        <%= link_to likeup_path( company.id ), remote: true do %>
                                            <span class="text hidden-xs hidden-sm">Like</span>
                                            <span class="like-icon"></span>
                                            <span class="separator "></span>
                                            <div class="like-count " id = "like-text-<%= company.id %>"><%= company.like %></div>
                                        <% end %>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="image-for-mobile hidden-lg hidden-md">
                            <%= image_tag "images-places-#{index+1}.png", class: 'img-responsive' %>
                        </div>
                        <div class="main-text-container">
                            <p>
                              <strong><%= index+1 %> of 10 Best <%= Category.find(company.category).name %> in SF</strong> - Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed
                              do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                              nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
                              dolor in reprehenderit in voluptate velit.
                            </p>
                        </div>
                        <div class="buttons-container">
                            <div class="learn-more-button"><%= link_to "LEARN MORE", place_path( url_code(Category.find(company.category).name), url_code( company.name ) ) %></div>
                            <div class="go-to-website-button"><a href="#">GO TO WEBSITE</a></div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--end of place container-->                          
<% end %>    
</section>
<!--End of places list section-->
<!--google map section-->
<section class="google-map-section">
    <div class="container-fluid no-padding">
        <div id="map"></div>
    </div>
</section>
<% @positions.each_with_index do |position, index| %>
  <div class="infobox-wrapper">
      <div id="infobox-<%= index %>" class="infoBox">
          <div class="google-map-arrow"></div>
          <%= image_tag 'place-google-map.png', class: "col-md-4 col-xs-4 no-padding" %>
              <div class="header-container col-md-8">
                 <div class="title-container">
                     <span class="title-text"><span style="color:#CF0F40; font-weight:bolder; font-size: 30px;"><%= index + 1 %> </span> <%= @companies[index].name %></span>
                     <div class="location-container"><span class="location-icon"></span><%= position['address'] %></div>
                 </div>
                 <!-- <div class="directions-container"><a href="#">DIRECTIONS</a></div> -->
                 <div class="footer-section">
                     <div class="buttons-container">
                         <a class="world-map" href="#"></a>
                         <span class="separator"></span>
                         <a class="mail" href="#"></a>
                         <span class="separator"></span>
                         <a class="phone" href="#"></a>
                     </div>
                 </div>
             </div>

      </div>
  </div>
<% end %>
<script type="text/javascript">
  function initialize() {
        
        var places = new Array();
        <% @positions.each do |position| %>
          places.push( new google.maps.LatLng(<%= position['lat'] %>, <%= position['lng'] %>) );
        <% end %>
        
        var pointMarkerImage = new Array();//store image of marker in array
        var pointMarker = new Array();//store marker in array

        var icon = '<%= asset_path("icon-google-map.png") %>';
        var iconHover = '<%= asset_path("icon-google-map-click.png") %>';

        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 14,
            center: places[0],
            panControl: false,
            scrollwheel: false,
            mapTypeId: google.maps.MapTypeId.ROADMAP            
        });

        var infoboxes = new Array();
        for ( var i = 0; i < places.length; i++ ){
            id = "infobox-" + i;
            infoboxes[i] = new google.maps.InfoWindow({
                                content: document.getElementById(id)
                              });
            pointMarkerImage[i] = new google.maps.MarkerImage('<%= asset_path("icon-google-map.png") %>');
            pointMarker[i] = new google.maps.Marker({
                position: places[i],
                map: map,
                icon: pointMarkerImage[i]
            });
            pointMarker[i].addListener('click', function(i) {
                                          return function() {
                                                      infoboxes[i].open(map, pointMarker[i]);
                                                  }
                                                }(i));
        }

    }

</script>

<script src="<%= Rails.application.secrets[:google_map_url] %>key=<%= Rails.application.secrets[:google_map_key] %>&callback=initialize" type="text/javascript"></script>
<!-- <script type="text/javascript" src="https://cdn.rawgit.com/googlemaps/v3-utility-library/master/infobox/src/infobox.js"></script>  -->
<!--end of google map section-->

releases/20180120164205/app/views/index/share_up.js.erb
$('#share-text-<%= @company.id %>').text("<%= @share %>");