releases/20180120164205/config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :firmware_images
  resources :wines
  resources :grapes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'sessions/new'

  get 'users/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'index#home'
  get '/about', to: 'index#about', as: 'about'
  get '/grow', to: 'index#grow', as: 'grow'
  get '/contact', to: 'index#contact', as: 'contact'
  get '/top-:category/:company', to: 'index#place', as: 'place'
  get '/top-:category', to: 'index#ranking', as: 'ranking'
  get '/search', to: 'index#search', as: 'search'
  get '/shareup/:id', to: 'index#share_up', as: 'shareup'
  get '/likeup/:id', to: 'index#like_up', as: 'likeup'
  get '/wines', to: 'wines#index'
  get '/wine_week', to: 'wines#week'
  get '/grape_week', to: 'grapes#week'
  get '/groups', to: 'groups#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
   resources :users
  
  scope 'admin' do
    resources :companies
  end

  root 'index#home'

end

releases/20180120164205/app/models/company.rb
class Company < ApplicationRecord
	validates :name, presence: true, uniqueness: true
	validates :category, presence: true
	validates :city, presence: true
end

releases/20180120164205/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
    get_info @company
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
    get_info @company
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit( :name, :city, :category)
    end
end

releases/20180120164205/app/helpers/companies_helper.rb
module CompaniesHelper
end

releases/20180120164205/app/views/companies/_form.html.erb
<%= form_for(company, class: 'form-horizontal') do |f| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Name:</label>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div><br><br>
  <div class="form-group">
    <label class="control-label col-sm-2" for="email">City:</label>
    <div class="col-sm-10">
      <%= f.text_field :city, :class => 'form-control' %>
    </div>
  </div><br><br>
  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Category:</label>
    <div class="col-sm-10 ">
     <%= f.select :category, options_for_select( Category.all.map {|category| [ category.name, category.id ]} ), :class => 'form-control' %>
    </div>
  </div><br><br>
  <div class="form-group"> 
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Submit", :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

releases/20180120164205/app/views/companies/edit.html.erb
<% provide(:title, "Edit #{@company.name}") %>
<% provide(:body_class, "company-page") %>

<div class="container">
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>
</div>

releases/20180120164205/app/views/companies/index.html.erb
<% provide(:title, "Best Companies") %>
<% provide(:body_class, "company-page") %>

<div class="container">
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>No</th>
      <th>Name</th>
      <th>City</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.id %></td>
        <td><%= company.name %></td>
        <td><%= company.city %></td>
        <td><%= company.category %></td>
        <td><%= link_to '<span class="glyphicon glyphicon-ok"></span>'.html_safe, company %></td>
        <td><%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_company_path(company) %></td>
        <td><%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>
</div>

releases/20180120164205/app/views/companies/new.html.erb
<% provide(:title, "New Company") %>
<% provide(:body_class, "company-page") %>

<div class="container">
	<h1>New Company</h1>

	<%= render 'form', company: @company %>

	<%= link_to 'Back', companies_path %>
</div>

releases/20180120164205/app/views/companies/show.html.erb
<% provide(:title, @company.name) %>
<% provide(:body_class, "company-page") %>

<div class="container">
<p id="notice"><%= notice %></p>

<div>
	No: <%= @company.id %>
</div>
<div>
	Name: <%= @company.name %>
</div>
<div>
	City: <%= @company.city %>
</div>
<div>
	Category: <%= @company.category %>
</div>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>
</div>