releases/20180120164205/config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :firmware_images
  resources :wines
  resources :grapes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'sessions/new'

  get 'users/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'index#home'
  get '/about', to: 'index#about', as: 'about'
  get '/grow', to: 'index#grow', as: 'grow'
  get '/contact', to: 'index#contact', as: 'contact'
  get '/top-:category/:company', to: 'index#place', as: 'place'
  get '/top-:category', to: 'index#ranking', as: 'ranking'
  get '/search', to: 'index#search', as: 'search'
  get '/shareup/:id', to: 'index#share_up', as: 'shareup'
  get '/likeup/:id', to: 'index#like_up', as: 'likeup'
  get '/wines', to: 'wines#index'
  get '/wine_week', to: 'wines#week'
  get '/grape_week', to: 'grapes#week'
  get '/groups', to: 'groups#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
   resources :users
  
  scope 'admin' do
    resources :companies
  end

  root 'index#home'

end

releases/20180120164205/app/models/firmware_image.rb
class FirmwareImage < ApplicationRecord
end

releases/20180120164205/app/controllers/firmware_images_controller.rb
class FirmwareImagesController < InheritedResources::Base

  private

    def firmware_image_params
      params.require(:firmware_image).permit()
    end
end

releases/20180120164205/app/helpers/firmware_images_helper.rb
module FirmwareImagesHelper
end

releases/20180120164205/app/views/firmware_images/_form.html.erb
<%= form_for(firmware_image) do |f| %>
  <% if firmware_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(firmware_image.errors.count, "error") %> prohibited this firmware_image from being saved:</h2>

      <ul>
      <% firmware_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

releases/20180120164205/app/views/firmware_images/edit.html.erb
<h1>Editing Firmware Image</h1>

<%= render 'form', firmware_image: @firmware_image %>

<%= link_to 'Show', @firmware_image %> |
<%= link_to 'Back', firmware_images_path %>

releases/20180120164205/app/views/firmware_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Firmware Images</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @firmware_images.each do |firmware_image| %>
      <tr>
      	<td><%= firmware_image.firmware_image_filename %></td>
      	<td><%= image_tag '/uploads/alphasearch.png', class: 'img-responsive', alt: 'brunch places in San Francisco' %></td>
        <td><%= link_to 'Show', firmware_image %></td>
        <td><%= link_to 'Edit', edit_firmware_image_path(firmware_image) %></td>
        <td><%= link_to 'Destroy', firmware_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Firmware Image', new_firmware_image_path %>

releases/20180120164205/app/views/firmware_images/new.html.erb
<h1>New Firmware Image</h1>

<%= render 'form', firmware_image: @firmware_image %>

<%= link_to 'Back', firmware_images_path %>

releases/20180120164205/app/views/firmware_images/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_firmware_image_path(@firmware_image) %> |
<%= link_to 'Back', firmware_images_path %>